name: Uğrak Projesi Otomasyonu

on:
  schedule:
    # Her 30 dakikada bir çalışır
    - cron: "*/30 * * * *"
  workflow_dispatch: # Manuel çalıştırmak için

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Space'i Uyanık Tut (Ping)
        run: |
          curl -I https://hakgul-ugrak-sbert-model.hf.space/

      - name: Vektörleri Senkronize Et (Sync)
        run: |
          curl -X GET https://hakgul-ugrak-sbert-model.hf.space/sync-vectors
